SELECT * FROM PRT.SPOOLRELATORIO A WHERE A.CODSPOOLREL LIKE '%RAT%';
--INSERT INTO PRT.SPOOLRELATORIO (CODSPOOLREL, NOMEAMIGAVELSPOOLREL, DESCFINALIDADESPOOLREL, NOMEARQMODELO, CODTIPOPROCESSAMENTO, QTDTEMPOESPERA, IDRETORNORELATORIO)
--VALUES ('RAT034', NULL, NULL, 'RelatorioMovimentacaoAssociadoSobras', 1, 600, 321);

select * from rat.RATEIOPERDA WHERE DATACALCULO='2021-11-05'; 
select sum(VALORRATEIO) from rat.DESTINORATEIOPERDA WHERE DATACALCULO='2021-11-05'; 
select sum(VALORRATEIO-VALORABATIMENTO)  from rat.CONTROLERATEIOPERDA WHERE DATACALCULO='2021-11-05' and CODTIPODESTINORATEIO=8; 
select sum(VALORRATEIO) from rat.CONTROLERATEIOPERDA WHERE DATACALCULO='2021-11-05' and CODTIPODESTINORATEIO=9; 

select * from rat.ESTORNORATEIO WHERE DATACALCULO='2022-11-07';
--QUERY ALIMENTAR COMBO
SELECT * FROM RAT.HISTORICORATEIOMOVIMENTACAOPERDA WHERE IDINSTITUICAO = 29 order by DATAHORAATUALIZACAO desc;
SELECT * FROM RAT.RATEIOMOVIMENTACAOPERDA WHERE IDINSTITUICAO = 29 and idpessoa=5294812;
SELECT * FROM RAT.TIPOMOVIMENTACAOPERDA
select * from cli.viw_pessoa WHERE IDPESSOA in(5294812);
select * from RAT.RATEIOREINFMOVIMENTACAO

select * from rat.ESTORNORATEIO where idinstituicao=29 and  DATACALCULO='2022-11-07'
SELECT *
  FROM RAT.ESTORNORATEIO
 WHERE DESCCHAVELANCAMENTO = 'CCO|29|2507202221302224'
  WITH UR;

select * from rat.rateioago WHERE DATACALCULO='2022-11-07' and idinstituicao=29 
select * from rat.SOLICITACAOCARGARATEIO  where idinstituicao=29 order by IDSOLICITACAOCARGARATEIO desc

select * from rat.TIPODESTINACAORATEIO;
select sum(valorcalculado)from rat.RATEIOCALCULADOPERDA WHERE DATACALCULO='2021-11-05' AND IDINSTITUICAO=29;
select * from rat.VALORBASE WHERE DATACALCULO='2022-11-07' AND IDINSTITUICAO=29 and idpessoa=23517697;
select sum(valorrateio) from rat.CONTROLERATEIOPERDA WHERE IDINSTITUICAO=29 and DATACALCULO='2021-11-05' and CODTIPODESTINORATEIO=9;
select sum(valorrateio) from rat.RATEIO WHERE  IDINSTITUICAO=29 and idpessoa=5293386;
select * from rat.RATEIOMOVIMENTACAOPERDA WHERE IDINSTITUICAO=29  AND idpessoa =3499892;; 
select * from rat.CONTROLERATEIOPERDACRITERIO WHERE IDINSTITUICAO=29; 
select * from rat.DESTINORATEIO WHERE DATACALCULO='2022-06-14' and DESCCHAVELANCAMENTO= '20220614|29|RAT22072022112146' ;

SELECT * FROM RAT.RATEIOMOVIMENTACAOPERDA WHERE IDINSTITUICAO = 29 AND idpessoa in(7571621,5000289);
SELECT * FROM RAT.CONTROLERATEIOPERDA WHERE IDINSTITUICAO = 29 and idpessoa in(7571621);
select * from rat.RATEIOCALCULADO WHERE DATACALCULO='2022-11-07' and idinstituicao=29 AND IDPESSOA in(3643286,4690424,750739);
select * from rat.TIPODESTINORATEIO
select * from cco.contacorrente where  IDCONTACORRENTE in(10701482,10701571) and idinstituicao=29

select * from rat.ESTORNORATEIO where idinstituicao=29 and  DATACALCULO='2022-11-07';
select * from rat.DESTINORATEIO where  DATACALCULO='2022-11-07' and idinstituicao=29; --AND IDPESSOA in(5000289,5303197);

select * from rat.RATEIOPERDA WHERE IDINSTITUICAO=29 and DATACALCULO='2021-11-05';
select * from rat.RATEIOAPROVAFLUXO where IDINSTITUICAO=29  and IDOCORRENCIAPROCESSO in(268584968,268581321);
select * from rat.RATEIOAPROVAFLUXO where IDINSTITUICAO=29  and IDREGISTROCONTROLADO  in(20221107030129);

select * from rat.DESTINORATEIOPERDA d  
where  DATACALCULO='2022-11-07'
 and idinstituicao=29; 
 --and CODTIPODESTINORATEIO=1;

 SELECT *
  FROM CCO.VIW_CONTACORRENTE A
WHERE A.IDINSTITUICAO = 29
   AND A.IDPESSOA = 101415;
  
select * from rat.CONTROLERATEIOPERDA c  where  DATACALCULO='2022-11-07' and idinstituicao=29 and idcontacapital in(67,27662)  

--select * from cca.contacapital where idcontacapital in(26168,6377)  and idinstituicao=29
select * from cca.contacapital where idinstituicao=29 and numcontacapital in(41937);
select * from cco.contaCorrente where idInstituicao = 29  and idcontacorrente = 5293305;

--Consultar pessoas com pendência ou restrição no rateio
select *  from rat.EXCLUIPARTICIPANTERATEIO where IDINSTITUICAO=29 and DATACALCULO = '2022-11-07'; 
select IDCONTACORRENTE,numcontacorrente, CODSITUACAOCCO from cco.contacorrente where IDCONTACORRENTE=10701473 and IDINSTITUICAO=29;
select * from cco.contacorrente where numcontacorrente=10701473 and IDINSTITUICAO=29;

select * from rat.HISTORICODESTINORATEIOPERDA WHERE DATACALCULO='2022-11-07';
select sum(valorbase) from rat.VALORBASE where  DATACALCULO='2021-02-03' and idinstituicao=29;

SELECT * FROM ADM.MODALIDADEPRODUTO A WHERE A.IDINSTITUICAO = 29 AND
 A.IDPRODUTO = 7 AND A.IDMODALIDADEPRODUTO = 1075;
select * from rat.TIPODESTINORATEIO


select * FROM RAT.RATEIOago where DATACALCULO='2022-11-07';
select sum(valorrateado)FROM RAT.RATEIOCALCULADO where DATACALCULO='2022-11-07';
select * FROM RAT.RATEIOPERDA  where DATACALCULO='2022-11-07';

select * FROM RAT.CONTROLERATEIOPERDA  where DATACALCULO='2021-11-05'
select * FROM RAT.TIPODESTINORATEIO ;


select * FROM RAT.CONTROLERATEIOPERDA where idpessoa=5293304;
select * from RAT.RATEIOCALCULADO where DATACALCULO='2022-11-07' ;
         
select * FROM RAT.rateioago where  DATACALCULO='2021-02-03'

select * from rat.TIPODESTINORATEIO
select * from rat.RATEIOCALCULADOCANAL where IDINSTITUICAO=29 and DATACALCULO='2020-02-28';
select * from rat.CRITERIORATEIO where IDINSTITUICAO=29 and  DATACALCULO='2020-02-28';
select * from rat.FORMULARATEIO WHERE IDINSTITUICAO=29 and DATACALCULO='2020-02-28';
select * from rat.DISTRIBUIRATEIO WHERE IDINSTITUICAO=29 and DATACALCULO='2021-02-03'; ---Tabela populada quando rateio é controlado por operação


--Consultar os valores gerados para o rateio
---rateio calculado canal serve para o pessoal dos canais consultar o rateio no celular e ver o extrato

select * from rat.valorbase where IDINSTITUICAO=29 and dataCalculo ='2022-11-07';
select sum(valorrateado) from rat.RATEIOCALCULADO where IDINSTITUICAO=29 and dataCalculo ='2021-02-03';
select *  from rat.DESTINORATEIO where IDINSTITUICAO=29 and IDPESSOA=6261500;
select sum(valorcalculado) from rat.RATEIOCALCULADONEGATIVO where IDINSTITUICAO=29 and dataCalculo = '2021-02-03';

select sum(valorrateio) from rat.DISTRIBUIRATEIO WHERE IDINSTITUICAO=29 and DATACALCULO='2020-10-28';

---Acompanhar o processamento de valor base, rateio calculado etc
Select * from rat.SOLICITACAOCARGARATEIO order by DATAHORASOLICITACAOCARGA DESC;

---Apos a destinação do rateio consultar os valores lançados em conta capital
select sum(valorlancamento) from CCA.LANCAMENTOCONTACAPITAL WHERE IDINSTITUICAO = 29  
AND IDTIPOHISTORICO in(108,208)  and datalancamento='2022-11-07';

---Consultar lançamentos de estorno do rateio calculado
select sum(valorlancamento) from CCA.LANCAMENTOCONTACAPITAL WHERE IDINSTITUICAO = 29
 AND IDTIPOHISTORICO in(199,299) and datalancamento='2022-11-07';

select * from CCA.TIPOHISTORICOCCA where IDTIPOHISTORICO in(99,199,299);

select * from cca.contacapital where IDINSTITUICAO=29 and numcontacapital=86
select * from rat.DESTINORATEIO where IDINSTITUICAO=29 and DATACALCULO = '2021-02-03' and idpessoa=5293401

select * from rat.CONTROLAOPERACAORATEIO;
select * from rat.ESTORNORATEIO;
Select * from CLI.viw_pessoa where IDPESSOA=742331;

 Select * from CCA.CONTACAPITAL C
    INNER JOIN CLI.VIW_PESSOA P
    ON C.IDINSTITUICAO = P.IDINSTITUICAO
    AND C.IDPESSOA = P.IDPESSOA
    WHERE C.IDINSTITUICAO = 29;
    

--select * from adm.FECHAMENTOPRODUTOINST WHERE IDINSTITUICAO = 29
--CPF COM CONTA CAPITAL 59493275434
select sum (valorrateio) from Rat.DestinoRateio WHERE IDINSTITUICAO = 29 and DataCalculo = '2020-10-28' and IDCONTACORRENTE IS NULL;


 Select
            V.NUMFORMULARATEIO, V.DATACALCULO,
            V.BOLAUTOMATICO, P.IDPESSOALEGADO , P.NOMEPESSOA AS DESCNOMEPESSOA,
            V.IDINSTITUICAO, V.IDPESSOA
            from RAT.VALORBASE V
            INNER JOIN CLI.VIW_PESSOA P
            ON V.IDINSTITUICAO = P.IDINSTITUICAO
            AND V.IDPESSOA = P.IDPESSOA
            WHERE V.DATACALCULO = '2021-02-02' AND V.IDINSTITUICAO = 29
            ORDER BY P.NOMEPESSOA;
 ----consulta pra saber pessoas que não estão na viw pessoa do capes           
Select A.*
from RAT.DestinoRateio AS A
left join CLI.VIW_PESSOA AS B
ON A.IDINSTITUICAO = B.IDINSTITUICAO
AND A.IDPESSOA = B.IDPESSOA
WHERE A.DATACALCULO = '2022-11-07' AND A.IDINSTITUICAO = 29 and b.IDPESSOA is null

     SELECT * FROM CCA.CONTACAPITAL C
    INNER JOIN CLI.VIW_PESSOA P
    ON C.IDINSTITUICAO = P.IDINSTITUICAO
    AND C.IDPESSOA = P.IDPESSOA
    WHERE C.IDINSTITUICAO = 611;
    

----Consultas para verificar idpessoa 
  
SELECT COUNT (IDPESSOA), IDINSTITUICAO FROM CCA.CONTACAPITAL C 
WHERE IDPESSOA = 6818
GROUP BY IDINSTITUICAO;


Select COUNT(1) FROM CCA.CONTACAPITAL C 
WHERE C.IDINSTITUICAO = 29
AND IDPESSOA = 6818;

    
Select C.IDINSTITUICAO, COUNT(1) from CCA.CONTACAPITAL C 
INNER JOIN CCO.VIW_CONTACORRENTE O
ON O.IDPESSOA = C.IDPESSOA
AND O.IDINSTITUICAO = C.IDINSTITUICAO
WHERE C.IDINSTITUICAO = 378
GROUP BY C.IDINSTITUICAO ;


Select C.IDINSTITUICAO, COUNT(1) from CCA.CONTACAPITAL C 
INNER JOIN CLI.VIW_PESSOA O
ON O.IDPESSOA = C.IDPESSOA
AND O.IDINSTITUICAO = C.IDINSTITUICAO
--WHERE C.IDINSTITUICAO = 378
GROUP BY C.IDINSTITUICAO ;




Select C.* From CCA.CONTACAPITAL C
INNER JOIN CLI.VIW_PESSOA P
ON P.IDPESSOA = C.IDPESSOA
AND P.IDINSTITUICAO = C.IDINSTITUICAO
WHERE C.IDINSTITUICAO = 29;


select * from adm.FECHAMENTOPRODUTOINST where IDPRODUTO IN(2,5) AND IDINSTITUICAO=29;
--update cca.contacapital set VALORSALDOSUBSC ='99999999' where NUMCONTACAPITAL in (22226, 24030, 27818, 31543, 32581, 33121, 38707 );
    
select * from rat.RATEIOCALCULADO where IDINSTITUICAO=29 and dataCalculo = '2022-11-07';
select sum(VALORRATEADO) from rat.RATEIOCALCULADO where IDINSTITUICAO=29 and dataCalculo = '2022-11-07';
select *  from rat.DISTRIBUIRATEIO where IDINSTITUICAO=29 and dataCalculo = '2022-11-07'
select sum(VALORRATEIO) from rat.DESTINORATEIO where IDINSTITUICAO=29 and dataCalculo = '2021-02-03' AND DATADESTINO IS not NULL    
select COUNT(ipessoa) from rat.RATEIOCALCULADO;

Select DISTINCT IDPESSOA from RAT.RATEIOCALCULADO WHERE IDINSTITUICAO = 29 and DataCalculo = '2021-02-03';
select * from rat.DISTRIBUIRATEIO where IDINSTITUICAO=29 and dataCalculo = '2021-02-03' and idpessoa IN(744082,744089,744095)
select * from CLI.VIW_PESSOA where idpessoa IN(5293401);
select * from CLI.VIW_PESSOA where NUMCPFCNPJ IN ('26483070608');


select * from rat.FORMULARATEIO WHERE DATACALCULO='2022-11-07'

INSERT INTO RAT.VALORBASE (IDINSTITUICAO, DATACALCULO, NUMFORMULARATEIO, IDPRODUTO, IDMODALIDADEPRODUTO, IDTIPOINFOACUMULO, IDCONTACAPITAL, IDPESSOA, VALORBASE, VALORBASEAUXILIAR, BOLAUTOMATICO, DATAHORAATUALIZACAO)
SELECT
IDINSTITUICAO, '2021-06-03', NUMFORMULARATEIO, IDPRODUTO, IDMODALIDADEPRODUTO, IDTIPOINFOACUMULO, IDCONTACAPITAL, IDPESSOA, VALORBASE, VALORBASEAUXILIAR, BOLAUTOMATICO, DATAHORAATUALIZACAO
FROM RAT.VALORBASE A
WHERE A.IDINSTITUICAO = 29
AND A.DATACALCULO = '2021-02-03'
;



INSERT INTO RAT.CRITERIORATEIO (IDINSTITUICAO, DATACALCULO, NUMFORMULARATEIO, IDPRODUTO, IDMODALIDADEPRODUTO, IDTIPOINFOACUMULO)
SELECT IDINSTITUICAO, '2021-06-03', NUMFORMULARATEIO, IDPRODUTO, IDMODALIDADEPRODUTO, IDTIPOINFOACUMULO FROM RAT.CRITERIORATEIO A
WHERE A.IDINSTITUICAO = 29
AND A.DATACALCULO = '2021-02-03'



select * from cca.contacapital where IDINSTITUICAO=29 and idusuario <> 'USR_REPLICACAO_CCA';
select sum(valorcalculado) from rat.RATEIOCALCULADOPERDA where DATACALCULO = '2021-02-03'
select  sum(valorrateio) from rat.DESTINORATEIOPERDA where DATACALCULO = '2021-02-03'


---IPESSOA= 2406
--IPESSOA CORRETO = 85333

select * from rat.valorbase where DATACALCULO = '2022-11-07';

select * from rat.RATEIOCALCULADO where DATACALCULO = '2022-11-07' and VALORCONTACORRENTE is not null;

select * from rat.SOLICITACAOCARGARATEIO where DATACALCULO = '2022-11-07'

select *  from rat.CONTROLERATEIOPERDA where IDPESSOA=6470961;
select *  from rat.TIPODESTINORATEIO
select *  from rat.HISTORICOCONTROLERATEIOPERDA where CODSITUACAOCONTROLERATEIO=11
--update rat.RATEIOAPROVAFLUXO set codsituacaoaprovacao = 8 where numsolicitacaoaprovacao in(18,17,7,6,13,15,8,14,16,12);

select *  from  rat.RATEIOAPROVAFLUXO order by DATAHORASOLICITACAO desc;

select * from cco.contacorrente where numcontacorrente in (633011,690945,879410) and IDINSTITUICAO=29;

--delete from rat.RATEIOCALCULADO where DATACALCULO = '2022-11-07';
select sum(VALORrateado) from rat.RATEIOCALCULADO where DATACALCULO = '2022-11-07';
select sum (VALORRATEIO) from rat.DESTINORATEIO where DATACALCULO = '2022-11-07' ;
select sum (VALORRATEIO)from rat.DISTRIBUIRATEIO where DATACALCULO = '2022-11-07' ;

select * from rat.HISTORICODESTINORATEIOPERDA where DATACALCULO = '2022-11-07' ;
select * from rat.HISTORICOCONTROLERATEIOPERDA
select sum(VALORABATIDO) from rat.RATEIOCALCULADO where DATACALCULO = '2022-11-07';

select * from  RAT.DISTRIBUIRATEIO where DATACALCULO = '2022-11-07';
select * from rat.DESTINORATEIO where DATACALCULO = '2022-11-07';

select * from  RAT.DESTINORATEIOPERDA where DATACALCULO = '2021-02-03';
select sum (valorrateio)from rat.CONTROLERATEIOPERDA where datacalculo= '2022-11-07';
select * from rat.RATEIOAPROVAFLUXO order by id
select * from rat.RATEIOCALCULADO where DATACALCULO = '2022-11-07' and idpessoa=5305167;
select sum(valorrateado ) from rat.RATEIOCALCULADO where DATACALCULO = '2022-11-07';

select sum(valorrateio) from rat.destinorateio where DATACALCULO = '2022-11-07';

select sum(valorrateio) from rat.DISTRIBUIRATEIO where DATACALCULO = '2022-11-07';
select * from rat.CONTROLERATEIOPERDA where datacalculo='2021-02-03';

select * from rat.DESTINORATEIOPERDA where datacalculo='2022-11-07';
select * from rat.DESTINORATEIOPERDA where datacalculo='2021-02-03';
select * from rat.CONTROLERATEIOPERDA where datacalculo='2021-02-03' ;

select * from rat.RATEIOPERDA where  DATACALCULO ='2021-11-05'; 
select * from rat.CRITERIORATEIOPERDA
select * from rat.HISTORICOCONTROLERATEIOPERDA where datacalculo='2022-11-07' and CODSITUACAOCONTROLERATEIO=11;
select * from rat.HISTORICODESTINORATEIOPERDA where DATACALCULO = '2021-02-03';

select * from rat.SITUACAOCONTROLERATEIO
select * from rat.SITUACAODESTINORATEIO
select * from rat.RATEIOMOVIMENTACAOPERDA where idpessoa=5305167;
select * from rat.CONTROLERATEIOPERDACRITERIO
select sum (valorrateio) from rat.CONTROLERATEIOPERDA where DATACALCULO ='2022-11-07' and valorabatimento < valorrateio;

select * from rat.RATEIOPERDA r  where DATACALCULO ='2022-11-07';
select * from rat.VALORBASEPERDA v where DATACALCULO ='2022-11-07';
select *  from rat.RATEIOCALCULADOPERDA  where datacalculo='2022-11-07';


/** Consulta relatório de controle de perdas
SELECT
A.IDINSTITUICAO, A.DATACALCULO, B.NUMCPFCNPJ, B.NOMECOMPLETO, A.VALORRATEIO, A.VALORRATEIOATUAL, C.DESCDESTINORATEIO
FROM
RAT.DESTINORATEIOPERDA A INNER JOIN CLI.VIW_PESSOA B
ON A.IDINSTITUICAO = B.IDINSTITUICAO
AND A.IDPESSOA = B.IDPESSOA
INNER JOIN RAT.TIPODESTINORATEIO C
ON A.CODTIPODESTINORATEIO = C.CODTIPODESTINORATEIO
WHERE
A.IDINSTITUICAO = 29
AND A.DATACALCULO = '2021-02-03'
AND A.CODTIPODESTINORATEIO = 8
AND A.CODSITUACAODESTINORATEIO != 9
;**/

select * from rat.rateioago where DATACALCULO = '2022-11-07';
select * from rat.DESTINORATEIOPERDA where DATACALCULO = '2022-11-07';

select * from rat.CONTROLERATEIOPERDA where IDPESSOA=5305167;
select sum(valorrateio - valorabatimento) from rat.CONTROLERATEIOPERDA where datacalculo='2021-02-03' AND CODSITUACAOCONTROLERATEIO <> 9;

select sum(valorrateio) from rat.destinorateio where  DATACALCULO = '2022-11-07'
select sum(valorrateio) from rat.DISTRIBUIRATEIO where  DATACALCULO = '2022-11-07'

select  * from rat.repa where  DATACALCULO = '2022-11-07' and idpessoa=4393086
select sum(valorrateado) from rat.RATEIOCALCULADO where DATACALCULO = '2022-11-07';

CALL RAT.SPU_RAT_DESTPERDA_ATUALIZAR_PROXEXERCICIO(29, '2022-11-07', NULL);
select sum(valorabatido) from rat.RATEIOCALCULADO where DATACALCULO = '2022-11-07';

select * from rat.SITUACAOCONTROLERATEIO
 
select * from cco.contacorrente where IDINSTITUICAO=29 and NUMCONTACORRENTE=703281
--DELETE from rat.DESTINORATEIOPERDA where DATACALCULO = '2022-06-14';
--delete  from rat.CONTROLERATEIOPERDA where DATACALCULO = '2021-02-03';
--DELETE from rat.DESTINORATEIOPERDA where DATACALCULO = '2022-11-07' ;
-- delete  from rat.CONTROLERATEIOPERDA where DATACALCULO = '2022-11-07' ;

CALL RAT.SPU_RAT_DESTPERDA_ATUALIZAR_PROXEXERCICIO(29, '2022-11-07', '2022-11-07');
--DELETE FROM RAT.CONTROLERATEIOPERDA where DATACALCULO = '2022-06-14' ;
SELECT * FROM RAT.VALORBASEPERDA WHERE DATACALCULO = '2022-11-07' ;
SELECT * FROM RAT.RATEIOPERDA
SELECT * FROM RAT.RATEIOAGO where DATACALCULO = '2022-11-07' ;

SELECT SUM (VALORCALCULADO) FROM RAT.RATEIOCALCULADOPERDA r where DATACALCULO =  '2022-11-07';
SELECT SUM (VALORRATEIO) FROM RAT.DESTINORATEIOPERDA d where DATACALCULO =  '2022-11-07';
SELECT SUM (VALORRATEIOATUAL) FROM RAT.DESTINORATEIOPERDA d where DATACALCULO =  '2022-11-07';
SELECT count (*) FROM RAT.DESTINORATEIOPERDA d where DATACALCULO =  '2022-11-07';

SELECT SUM (VALORRATEIO) from rat.CONTROLERATEIOPERDA where DATACALCULO = '2022-11-07';

select * from rat.RATEIOMOVIMENTACAOPERDA ORDER BY DATAHORACADASTRO  DESC;
select * from rat.destinorateioperda WHERE IDPESSOA  =  6237235;
select * from rat.TIPODESTINACAORATEIO t 
SELECT * FROM CLI.VIW_PESSOA vp WHERE idpessoa = 101415;
SELECT *
  FROM CCO.VIW_CONTACORRENTE A
WHERE A.IDINSTITUICAO = 29
   AND A.IDPESSOA = 101415;
   
  --ACHAR INSTITUICAO
  SELECT DESCNOMECOOP,NUMCOOPPAI, NUMCOOPERATIVA, IDINSTITUICAO FROM SCI.VIW_INSTITUICAO WHERE NUMCOOPERATIVA = 701 AND NUMCOOPPAI = 1002;
